steps:
  - command: 
    - cd projects/hands-on-labs
    - git checkout ${HOL_BRANCH}
    - cd ../..
    - npm i
    - npm run test:labs:ci
    env:
      NG_CLI_ANALYTICS: ci
    plugins:
      - docker#v3.7.0:
          image: "acloudgurudevs/acg:12.14.0"
          propagate-environment: true