steps:
  - command:
      - "npm install"
      - "npm run ng lint"
      - "npm run ng deploy"
      - "npx angular-cli-ghpages — dir=dist/cc-test"
    env:
      NG_CLI_ANALYTICS: ci
    plugins:
      - docker#v3.7.0:
          image: "node:12.11.1"
          propagate-environment: true
